MULTI_STEP_RESET_CTX = "time_off_multi_step_reset_skip"
SKIP_RESPONSIBLE_SUBMIT_NOTIFY_CTX = "skip_responsible_submit_notify"
SKIP_OUTCOME_BOT_NOTIFY_CTX = "skip_outcome_bot_notify"

MAX_EMPLOYEE_HR_RESPONSIBLES = 15
MAX_EMPLOYEE_HR_RESPONSIBLES_MULTI_DIRECTOR = 40
DIRECTOR_JOB_TITLE_KEY = "giám đốc"
