user = env["res.users"].search([("login", "=", "nhi.cao@sangtam.com")], limit=1)
print("groups", user.group_ids.mapped("full_name"))
print("has hr_user", user.has_group("hr.group_hr_user"))
print("has hr_manager", user.has_group("hr.group_hr_manager"))
print("has supporter", user.has_group("hr_employee_hrm_detail.group_hr_employees_supporter"))
print("has staff", user.has_group("hr_employee_hrm_detail.group_hr_employees_staff"))
print("scope stored", user.hr_user_workforce_scope)
user.invalidate_recordset(["hr_user_workforce_scope"])
user._compute_hr_user_workforce_scope()
print("scope recomputed", user.hr_user_workforce_scope)
rule = env.ref("hr_employee_hrm_detail.hr_employee_officer_mien_rule", raise_if_not_found=False)
if rule:
    print("rule uses scope", "hr_user_workforce_scope" in (rule.domain_force or ""))
    print("rule snippet", (rule.domain_force or "")[:400])
domain = env["ir.rule"].with_user(user)._compute_domain("hr.employee", "read")
print("computed domain", domain)
